modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/shedaniel/ClothConfig/issues/"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge/"
logoFile="icon.png"
authors="shedaniel"
license="Unlicense"
[[mods]]
modId="cloth-config"
version="4.0"
displayName="Cloth Config v4 API"
description='''
An API for config screens.
'''